### PR TITLE
Added WhitePaper for Korean

### PR DESCRIPTION
**Pull request by JEJEKR**
Added Whitepaper file translated into Korean.
Discord ID : @jeje_kr
Twitter : @KOR_JEJE

### CODE REVIEW

**Comment by DavidAJohnston** [comment]
Cool. Thanks. Please combine hour requests with code contributions. See best practices here.
https://github.com/MorpheusAIs/Morpheus/blob/main/Code%20Contributor%20Best%20Practices.md

**Comment by DavidAJohnston** [comment]
Updated link. https://github.com/MorpheusAIs/Morpheus/blob/main/!KEYDOCS%20README%20FIRST!/8.Code%20Contributor%20Best%20Practices.md

**Comment by JEJEKR** [comment]
Thx! I added my contribution history in Proof_Of_Contribution.md
Tell me whenever if there are some feedbacks.

**Comment by DavidAJohnston** [comment]
Thanks. Can't merge due to this conflict.
Conflicting files
Contributions/Code - Proof_Of_Contribution.md
Try again : )

**Comment by DavidAJohnston** [comment]
Still a conflict. I'll merge this manually. Just to let you know there are no additional hours for the translation tasks as the major languages are now well covered.

**Comment by JEJEKR** [comment]
I've been really busy for a few days, so I couldn't care this. Really thx for your service :)

**Comment by JEJEKR** [comment]
I checked the whitepaper(international) folder, but I think Korean whitepaper is still not merged. Should I reopen the pull request with korean whitepaper file?

**Comment by JEJEKR** [comment]
I made a new pull request #438 
Thx

**Pull request closed without merging**
