### PR TITLE
Add MOR token base

### PR DESCRIPTION
**Pull request by kphed**
I believe in what you're doing at Morpheus and would love to contribute however I can codewise (you can view the notable/relevant pieces of my work at https://github.com/kphed).

In this PR, I've created a Forge project and added a minimal MOR token contract. If it looks fine, I can start implementing the remainder as my schedule allows.

### CODE REVIEW

**Comment by DavidAJohnston** [comment]
Thanks for your excitement about the Morpheus community and open source project.
There is a group that reached out and are pretty far along in preparing Smart Contracts for the Morpheus community. 
I think there may be a separate repo for the Smart Contracts and keep this repo focused on all things related to the Morpheus Full Node software. I'll make a comment here when things progress.

**Comment by DavidAJohnston** [comment]
Given your experience I'd love to see your comments on the Smart Contracts they have developed.

**Comment by kphed** [comment]
Thanks for filling me in on the details David. I'd be happy to review their contracts and provide feedback + contribute optimizations.

**Comment by DavidAJohnston** [comment]
See Testnet Smart Contracts provided by an open source contributor here.
https://github.com/MorpheusAIs/Morpheus/blob/main/TestnetSmartContracts.md

**Comment by kphed** [comment]
Thanks David. Do they have a public code repo where contributions can be made?

**Pull request closed without merging**
