### PR TITLE
0.0.3

### PR DESCRIPTION
**Pull request by betterbrand**
0.0.3
updated images and icons
native install on ubuntu

### CODE REVIEW

**Comment by DavidAJohnston** [comment]
Looks like there are some conflicts to resolve before this PR can merge.
README.md
YellowPaper.md
package-lock.json
package.json
ui/index.html
yarn.lock

**Comment by betterbrand** [comment]
On it today

**Review by betterbrand — COMMENTED** [review]
ok

**Review by betterbrand — COMMENTED** [review]
\

**Pull request merged**
