### PR TITLE
Update Code - Proof_Of_Contribution.md

### PR DESCRIPTION
**Pull request by Tigerbuidl**
Here is my pull request using the information @DavidAJohnston gave me. Thank you for your help

### CODE REVIEW

**Comment by Tigerbuidl** [comment]
I have updated this form in a new pull Request using the information that @DavidAJohnston  gave me. I have read this link and I think that my request is reasonable https://github.com/MorpheusAIs/Morpheus/blob/main/!KEYDOCS%20README%20FIRST!/8.Code%20Contributor%20Best%20Practices.md

**Comment by DavidAJohnston** [comment]
Thanks. There is a conflict and this PR can not be merged. Please update to latest. Thanks.

**Comment by Tigerbuidl** [comment]
to make sure it is the the latest file will you please send the file link to me. it will save trouble for both of us I think

**Comment by DavidAJohnston** [comment]
There is still a conflict. I'll merge this in manually. Just so you are aware there are no more hours available for translation tasks. The major languages are fairly well covered. And testing only earns hours if there is an improvement to a guide or a bug found. Thanks.

**Pull request closed without merging**
