### PR TITLE
LLM Transaction Response Validator

### PR DESCRIPTION
**Pull request by a1t3g0**
The current Metamask model logic assumes that the LLM JSON response for transacting is correct. 

Data validation is necessary for any LLM response to ensure (in this case) the JSON returned is correct and valid. This is very important as:

1. Base-model training is based on a corpus at a set date i.e. they may not have seen the latest updates to Metamask docs (or other API specs) and could return methods, format etc. that is no longer supported
2. Base-model hallucinations can cause a high confidence response of incorrect data. 
3. API errors will be harder to detect if we’re not certain the correct data was sent
4. Poor UX (user experience) is likely if we don’t manage the data information flow

Initial proposed solution builds on existing logic to minimise refactoring the code base: These include:
- [ ] TransactionParams: Created a new class called TransactionParams that checks the validity of the JSON response from LLM against Metamask specs
- [ ] TransactionRequest: Updated TransactionRequest class to incorporate TransactionParams. Also updated TransactionRequest to validate the method response from LLM is a valid Metamask method (and one that Morpheus wants to support) by adding a field_validator to check TransactionMethods dict
- [ ] TransactionMethods: Created a dictionary of supported Metamask Transaction methods. This also allows us to control the functionality we want to offer users as we test and scale LLM performance/capabilities.

Note: Class ethSendTransactions has been replaced with TransactionClass in order to support several Metamask transaction methods

Other improvements will be added in next PR - in consultation with the repository lead

### CODE REVIEW

**Review by DavidAJohnston — APPROVED** [review]

**Comment by DavidAJohnston** [comment]
Looks good to me. @betterbrand thoughts?

**Comment by betterbrand** [comment]
Looks good to me. I'd like Rakshak to review

**Comment by DavidAJohnston** [comment]
Moving this over to the new Docs repo.

**Comment by DavidAJohnston** [comment]
Closing this PR. Please move over to the new repo.

**Pull request closed without merging**
