### PR TITLE
rag-feature-branch

### PR DESCRIPTION
**Pull request by domsteil**
0. Imported Langchain promptTemplate and RunnablePassThrough APIs for user NLQ

1. Updated src/api.js to include sendMorpheusChat which can be triggered by /morpheus slash command in the chat. Agent requires Infura Key to make JSON RPC call... set env var process.env.INFURA_API_KEY

2. Updated src/client.js to include window.electronAPI.onMorpheusChatReply

### CODE REVIEW

**Comment by DavidAJohnston** [comment]
Thanks @domsteil you rock.
However there are a few conflicts in the PR. Here is the list.
.gitignore
forge.config.js
package-lock.json
package.json
yarn.lock

**Comment by DavidAJohnston** [comment]
@betterbrand want to take a crack at resolving these conflicts?

**Comment by betterbrand** [comment]
I'll go through em

**Comment by DavidAJohnston** [comment]
Closing this PR for now. Please move over to the new Repo.

**Pull request closed without merging**
