### PR TITLE
Protection funds doc translation

### PR DESCRIPTION
**Pull request by creeping-vampires**
## Changed 
- Add translation for Greek language 
- Add translation for Korean language
- Add translation for Indonation language
- Add translation for Arabic language
- Add translation for Hungarian language
- Add translation for Polish language
- Add translation for Portuguese language
- Add translation for Romanian language
- Add translation for Swedish language
- Add translation for Bulgarian language

### CODE REVIEW

**Comment by creeping-vampires** [comment]
@DavidAJohnston  Ser please review the pr

**Comment by DavidAJohnston** [comment]
1. There is a conflict for the PR.
Its likely in the line you picked to add the proof of hours.
Pick a line that isn't the very last one : )

**Comment by DavidAJohnston** [comment]
2. There aren't hours being offered for translations of papers right now as noted else where. The submission is missing a "Issue Link".
You are welcome to offer the code right now and if an Issue request is made for these translations, then you can claims hours at that point. Please see the Best Practices guide to avoid these types of issues in the future. 
https://github.com/MorpheusAIs/Morpheus/blob/main/!KEYDOCS%20README%20FIRST!/8.Code%20Contributor%20Best%20Practices.md

**Comment by creeping-vampires** [comment]
Thanks, I will keep that in mind  in next contributions. 

I will create an issue and point out to this pr

**Comment by DavidAJohnston** [comment]
There is still a conflict. I'll try and resolve it manually.

**Comment by DavidAJohnston** [comment]
Resolved and merging.

**Pull request merged**
