### PR TITLE
Refactor code to improve performance and readability

### PR DESCRIPTION
**Pull request by shamoons**
Removed yarn.lock file
Resolves https://github.com/MorpheusAIs/Morpheus/issues/555

### CODE REVIEW

**Review by DavidAJohnston — APPROVED** [review]
Looks good to me. @betterbrand any comment on yarn?

**Review by betterbrand — CHANGES_REQUESTED** [review]
More than the yarn lock was removed.

**Comment by shamoons** [comment]
> More than the yarn lock was removed.

Yup. Pinning dependencies provides certainty and visibility, as you know exactly which version of each dependency is installed at any time, benefiting both when upgrading versions and when rolling back in case of problems.

Also, there were some weird end of line characters in the `.md` file

**Comment by betterbrand** [comment]
@shamoons  You're preaching to the choir.  
I sent this in our chat to reference  TD structure. If the final push needs the cleaning, we can do it then.

**Comment by DavidAJohnston** [comment]
Thanks. Closing this PR. Please move chat over to new Repo. Thanks.

**Comment by DavidAJohnston** [comment]
Closing this PR. Please move conversation to the new repo.

**Pull request closed without merging**
